version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: faas
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: faas
    ports: ["5432:5432"]

  faas:
    build: .
    depends_on: [redis, postgres]
    environment:
      REDIS_URL: "redis://redis:6379/0"
      PG_URL: "postgres://faas:pass@postgres:5432/faas?sslmode=disable"
    ports: ["8080:8080"]
    command: ["./faas"]
